### ISSUE TITLE
sync: disableDownload -- Syncing files to / appears that devspace still processes index for entire container

### ISSUE THREAD

**Issue by harryttd** [devspace-sh/devspace#1218]
**What happened?**
My containers workdir is `/`. I set `containerPath: /`. It appears the container may be copying all files in root to local computer. Trying to set `disableDownload` did not help. Initial sync never finishes.

I left sync running once for a while and finally got an out of memory error.

Setting `downloadExcludePaths: ["/"]` worked however.

Thanks @LukasGentele for all your help.

**What did you expect to happen instead?**
With `disableDownload` initial sync should happen quickly and syncing should begin. Entire container index should not be processed.

**How can we reproduce the bug?** (as minimally and precisely as possible)
Have image with workdir `/`. Try syncing files to the container. That should hopefully reproduce as that is what I have going on.

**Local Environment:**

* DevSpace Version: \[use `devspace --version`\]: 5.2.2
* Operating System: mac
* Deployment method: kubectl apply

**Kubernetes Cluster:**

* Cluster: minikube
* Kubernetes Version: \[use `kubectl version`\]

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@harryttd thanks for opening this issue! Currently if the option `disableDownload ` is enabled, devspace will still try to gather the remote files once initially (in your case these are probably too many hence why it gets stuck). We have to do this to check which files are there and which files need to be uploaded initially, otherwise the initial sync would not work.  

By excluding `/` in the `downloadExcludePaths`, the remote side does not try to discover any files initially which is why it is a lot faster, however devspace will upload now all local files everytime the sync starts. The correct approach here is to exclude in the `downloadExcludePaths` the big folders that take devspace so long to parse or do a `!application` exclusion for example. We could also add an option to completely disable the initial sync as well if that is what you want.

**Comment by LukasGentele** [comment]
@FabianKramm we should document that `!` works in exclude paths
