### ISSUE TITLE
Can't force a space to sleep when port forwarding is running

### ISSUE THREAD

**Issue by danieleh11** [devspace-sh/devspace#1313]
**What happened?**
developer is using a space, once he leaves the space by mistake in port-forwarding (devspace dev)
i can put the space to sleep.

**What did you expect to happen instead?**
tried to force the space to sleep.

**How can we reproduce the bug?** (as minimally and precisely as possible)
run port forwarding on a space and try put the space to sleep.

**Local Environment:**

* DevSpace Version: \[use `devspace --version`\]
* Operating System: windows | linux | mac
* Deployment method: helm | kubectl apply

**Kubernetes Cluster:**

* Cloud Provider: google | aws | azure | DevSpace Cloud | DevSpace Cloud Enterprise | other
* Kubernetes Version: \[use `kubectl version`\]

**Anything else we need to know?**

/kind bug

**Comment by FabianKramm** [comment]
@danieleh11 thanks for opening this issue! We'll add an option for this to loft very soon. 

However, we were also thinking about adding an option to devspace to automatically exit after the user is inactive for a certain time period, which would help with your issue. What do you think about that?

**Comment by danieleh11** [comment]
Hey,
sounds good, can I control the time limit for how long if the user will be inactive?

**Comment by FabianKramm** [comment]
@danieleh11 yes we would add that

**Comment by danieleh11** [comment]
Great
Thanks.

**Comment by Chrislevi** [comment]
@FabianKramm Is there a status regarding this feature?

**Comment by FabianKramm** [comment]
@Chrislevi @danieleh11 unfortunately detecing mouse or keyboard input in golang is not a trivial task because of cross compiling issues and CGO, so I think we'll wait with implementing this feature until we find a way to do this without CGO.

Regarding the original problem, that a space cannot be forced sleeping: we added a new feature in loft [v1.7.0](https://github.com/loft-sh/loft/releases/tag/v1.7.0), where you can prevent spaces from waking up for a certain time frame, which should solve this problem.
