### ISSUE TITLE
Export Helm Charts

### ISSUE THREAD

**Issue by madhavajay** [devspace-sh/devspace#1704]
**Is your feature request related to a problem?**
Yes, currently when using devspace Component Helm Charts there is no way to get access to the temporary generated values.yaml file or to explicitly export the entire helm chart to a directory for manual modification or publishing.

**Which solution do you suggest?**
It would be really awesome if there was an export function similar to `devspace render` where it outputs a helm chart folder and all the related values and helmcharts sufficient to manually run `helm install` or to then change the `devspace.yaml` to use this new exported helm chart to manually tweak it.

**Which alternative solutions exist?**
None really.

**Additional context**
The simplest thing would be, getting access to the generated values file since it currently goes to a temp file which is immediately deleted, but it would be cool to go further and provide a full "output to helm chart" command.

/kind feature

**Comment by LukasGentele** [comment]
The component-chart is not really generated. It's a regular helm chart and you can download it from here: https://github.com/loft-sh/component-chart

The values for the chart are also just whatever you put in `values` or what is provided via `valuesFiles` in `devspace.yaml`, so I'm not sure if we need a separate export command for that.

**Comment by FabianKramm** [comment]
@madhavajay you can just do a:
```
git clone https://github.com/loft-sh/component-chart
```
and then use 
```
helm install my-app ./component-chart -n my-namespace -f values.yaml
```

**Comment by str11ngfello** [comment]
I ended up here searching for a way to use ArgoCD with devspace. ArgoCD just wants to point to git repo with a final, rendered helm chart for example. But seems I can't get that out of "devspace deploy" hmmmm. Devspace deploy is "push" and ArgoCD is "pull".

**Comment by LukasGentele** [comment]
I think you could include `devspace render` as a command via a argocd plugin: https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#environment

**Comment by str11ngfello** [comment]
Wow, actually I have to admit I just started using devspace a few nights ago. Hadn't see "render" command yet. Render into a manifest file and commit it. Brilliant. Thank you for pointing me to that.

**Comment by str11ngfello** [comment]
Just a quick followup. ArgoCD allows me to remove the need for kubectl in my Gitlab runner. Devspace looks like it tries to use kubectl to get namespaces by default? This won't work anymore because I don't have/want a valid kube context since ArgoCD will handle that. Any suggestion? I'm excited to pair devspace with GitOps and I'm getting close. See my gitlab runner fail because devspace build tried to get namespaces with kubectl. Thanks!
![image](https://user-images.githubusercontent.com/877000/155588797-7139e572-1c53-48aa-9b12-804b4ab19bd3.png)

**Comment by str11ngfello** [comment]
Ah, I found this - https://github.com/loft-sh/devspace/pull/1771

Kaniko in cluster build eh? Okay, makes sense then. Perhaps I need to use dind.

**Comment by computerquip-work** [comment]
I might be mistaken but doesn't the proposed solution require devspace to be installed? I think the intention of the issue is that devspace shouldn't need to be installed in order to function.

I've been looking at a few different solutions over the past few weeks and the name "Component Chart" confuses me because there is no chart to speak of. You do describe components but there's no chart, hence nothing to publish. There's an extra dependency here that requires extra setup in order to use. It's unorthodox compared to how charts are normally deployed.

**Comment by zerbitx** [comment]
The Devspace project currently lacks enough contributors to adequately respond to all issues. After 90d of inactivity,  the issue is closed. You can re-open this issue if you still want help.
