### ISSUE TITLE
[DEVSPACE UI] bind: can't assign requested address

### ISSUE THREAD

**Issue by afreyermuth98** [devspace-sh/devspace#2704]
**What happened?**  
I'm trying to use the `--host` flag on the `devspace ui` command to be able to access my UI hosted in my kubernetes cluster from an ingress.
My command is `devspace ui --host ui.mysuperdomain.com` and I get the following error : 
```
info Using namespace 'mynamespace'
info Using kube context 'mycontext'
info Start listening on http://ui.mysuperdomain.com:8090
fatal listen tcp X.X.X.X:8090: bind: cannot assign requested address
```

**What did you expect to happen instead?**  
I expect no issue or a more explicit error log to fix the issue 
```
info Start listening on http://ui.mysuperdomain.com:8090
```

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Even locally it doesn't work so you can just execute `devspace ui --host test.com`

**Local Environment:**  
- DevSpace Version: 6.3.2
- Operating System: mac
- ARCH of the OS:  ARM64 
**Kubernetes Cluster:**  
- Cloud Provider: aws
- Kubernetes Version: 1.25.7

**Anything else we need to know?**  
No

**Comment by lizardruss** [comment]
@afreyermuth98 Hello! Just to clarify, do you want to access the DevSpace UI, or an application that you've deployed to your kubernetes cluster?

The `devspace ui` command is for starting the DevSpace UI, which is a built in application for browsing the applications deployed to your cluster, view logs, and view the DevSpace Configuration.

If you'd like to view an application you're building, then using [Port Forwarding](https://www.devspace.sh/docs/configuration/dev/connections/port-forwarding) is likely the way to go. This doesn't require an ingress, since you'll access the application over `localhost:[FORWARDED_PORT]`, but you can add a `/etc/hosts` entry if you'd like to mimic it.

**Comment by afreyermuth98** [comment]
Hello @lizardruss , I know about that but what I want is to let the UI available for some developers that doesn't have access to the cluster / to let them see the UI without port forwarding etc ...
I've made the trick by editing `/etc/hosts` but maybe an easier solution could be cool :)

**Comment by lizardruss** [comment]
I see. The DevSpace UI actually runs on the local machine and not the cluster, so ingress / port-forwarding in the Kubernetes sense doesn't apply. I think having an `/etc/host` entry is probably the best option, since exposing the local machine over DNS etc is out of scope for DevSpace, and deploying the DevSpace UI to the cluster would be quite a refactoring.

Closing for now, but please reopen if I'm still misunderstanding the request.
