### ISSUE TITLE
TTL support

### ISSUE THREAD

**Issue by VagyokC4** [devspace-sh/devspace#2719]
**Which solution do you suggest?**  

Add support for TTL on deployments.  Adding / extending / removing.

**Additional context** 
 
I'd like to be able to deploy with a TTL.

The use case would be to deploy these ephemeral environments that automatically clean themselves up after some time.

**Comment by lizardruss** [comment]
Hello! Thanks for the feature request! Since DevSpace is a client only tool, the TTL may or may not work depending on whether the user's computer is still running. We don't have plans to introduce a server-side component to DevSpace, but there is a commercial offering that provides this exact functionality. If you'd like more information about that, I'm happy to provide it.

**Comment by VagyokC4** [comment]
Hi @lizardruss, thanks for the explanation.  Being a client only tool I can see the limitations of this feature.  I was under the assumption that you had some server side bits and could easily create a timer and trigger the cleanup.
